{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "generic.serviceAccountName" . }}
  labels:
{{ include "generic.labels" . | indent 4 }}
{{- end -}}
